docker_images:
  - name: grafana/grafana
    container_name: grafana
    restart_policy: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  - name: prom/prometheus
    container_name: prometheus
    restart_policy: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  - name: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    restart_policy: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  grafana-storage: {}
  prom_data: {}
