- name: Update apt package wajib
  apt:
    update_cache: yes
- name: Install dependensy yg diperlukan
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
- name: Tambahkan docker gpg key wajib satu kali saja
  apt_key:
    url: "{{ docker_gpg_key_url }}"
    state: present
- name: Tambahkan docker repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present
- name: Update apt repository
  apt:
    update_cache: yes
- name: Install Docker dan semua repository nya
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  notify:
    - Restart Docker
    - Start Docker
